### ISSUE TITLE
kryo exceptions

### ISSUE THREAD

**Issue by antonkulaga** [SANSA-Stack/SANSA-RDF#33] opened 2018-02-04 01:04 UTC
I constantly get out of bounds exceptions from kryo, despite using it as a default serizalizer:
Here is what I got from opening Gene Ontology file (I had to convert it to N3 before parsing):
```
org.apache.spark.SparkException: Job aborted due to stage failure: Exception while getting task result: com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 102, Size: 31
Serialization trace:
fTargetNamespace (org.apache.xerces.impl.dv.xs.XSSimpleTypeDecl)
fBase (org.apache.xerces.impl.dv.xs.XSSimpleTypeDecl)
typeDeclaration (org.apache.jena.datatypes.xsd.impl.XSDBaseStringType)
dtype (org.apache.jena.graph.impl.LiteralLabelImpl)
label (org.apache.jena.graph.Node_Literal)
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1504)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1732)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2050)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
  at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1354)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.take(RDD.scala:1327)
  ... 81 elided
```

**Comment by GezimSejdiu** [comment] 2018-02-09 14:14
Hi @antonkulaga ,
many thanks for posting the issue. In order to reproduce the issue, could you please send us the code snippets you are using when it throws this exception.
Like when loading the data:
```scala
val triples = spark.rdf(Lang.NTRIPLES)(path)
``` 
or somewhere else? and if possible could you send a sample dataset which raises this issue.

Best regards,

**Comment by earthquakesan** [comment] 2018-04-06 08:29
Link to GO ontology: http://geneontology.org/page/download-ontology

**Comment by GezimSejdiu** [comment] 2018-04-10 09:17
Thanks, @earthquakesan for sharing the ontology/dataset where I could try it out. 

Hi @antonkulaga , in order to reproduce the issue I downloaded [Go Ontology (go.owl)](http://purl.obolibrary.org/obo/go.owl) and run these code snippets : 
```scala
import net.sansa_stack.rdf.spark.io._
import org.apache.jena.riot.Lang

val input = "hdfs://namenode:8020/data/go.owl"

val lang = Lang.RDFXML
val triples = spark.rdf(lang)(input)
triples.take(5).foreach(println(_))
```
and I get this as a result : 
![image](https://user-images.githubusercontent.com/5259296/38547870-853b3e8e-3cb0-11e8-9e2f-a56c50e75bd6.png)
As we can see from the figure, SANSA is able to read RDF/XML format and gives us `1581306` triples. 

Please, could you do the same and let us know if the error persist.

Best regards,

**Comment by GezimSejdiu** [comment] 2018-04-11 13:40
Hi there,
I'm going to close this issue for now since I was able to read the go.owl file even without the need to transform to NTRIPLES/N3 serialization. 

In case there is still room for discussion related to this issue, please, feel free to comment and we can open the issue and investigate more.

Best regards,

**Comment by antonkulaga** [comment] 2018-05-04 10:28
With current rdf/xml code in the latest published vesin (0.3.0) I constantly get
```
import net.sansa_stack.rdf.spark.io._
import net.sansa_stack.rdf.spark.io.rdf._
import org.apache.jena.riot.Lang

val input = az("/go/go.owl")

val lang = Lang.RDFXML
val triples = spark.read.rdf(lang)(input)
triples.take(5).foreach(println(_))
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, 10.0.0.3, executor 0): java.lang.NullPointerException
	at org.apache.hadoop.conf.Configuration.<init>(Configuration.java:703)
	at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:442)
	at org.apache.hadoop.mapreduce.task.JobContextImpl.<init>(JobContextImpl.java:67)
	at org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl.<init>(TaskAttemptContextImpl.java:49)
	at org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl.<init>(TaskAttemptContextImpl.java:44)
	at org.apache.spark.sql.execution.datasources.HadoopFileLinesReader.<init>(HadoopFileLinesReader.scala:44)
	at net.sansa_stack.rdf.spark.io.rdfxml.TextInputRdfXmlDataSource$.readFile(RdfXmlDataSource.scala:110)
	at net.sansa_stack.rdf.spark.io.rdfxml.RdfXmlFileFormat$$anonfun$buildReader$1.apply(RdfXmlFileFormat.scala:87)
	at net.sansa_stack.rdf.spark.io.rdfxml.RdfXmlFileFormat$$anonfun$buildReader$1.apply(RdfXmlFileFormat.scala:85)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:136)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:120)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:124)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:174)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:105)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
```

**Comment by GezimSejdiu** [comment] 2018-05-04 11:10
Hi @antonkulaga ,
unfortunately, this is not released yet. It is only implemented on the `0.3.1-SNAPSHOT` version of SANSA. Soon we will have our next release and it will go with `0.4.0` version.

Could you please, try with [`0.3.1-SNAPSHOT`](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/pom.xml#L65) version of SANSA and let us know if the issue still persist. If so we can re-open this issue again.

Many thanks for your feedback.

**Comment by antonkulaga** [comment] 2018-05-04 11:27
I do not see 0.3.1-SNAPSHOT at Sonatype and I also get 
```
Found 149 errors
Found 53 warnings
```
When I try to:
```
mvn clean install
```
On current github version.

**Comment by GezimSejdiu** [comment] 2018-05-04 12:49
Hi @antonkulaga ,

yes, it is not on the Sonatype, there will be pushed only the stable releases:).

But you can get it via our [maven central repository](http://maven.aksw.org/repository/snapshots/net/sansa-stack/sansa-rdf-spark_2.11/), but for that, you have to include it as a [repository](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/pom.xml#L327,L337). 

Reg. the build of the project, that is strange. The jenkins says that the build is passing, and also it pass on my computer as well : 
```sh
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SANSA Stack - RDF Layer - Parent ................... SUCCESS [  2.114 s]
[INFO] sansa-rdf-common_2.11 .............................. SUCCESS [ 16.794 s]
[INFO] SANSA RDF API - Flink .............................. SUCCESS [ 29.097 s]
[INFO] sansa-rdf-spark_2.11 ............................... SUCCESS [ 45.580 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:33 min
[INFO] Finished at: 2018-05-04T14:47:50+02:00
[INFO] Final Memory: 104M/1641M
[INFO] ------------------------------------------------------------------------
```
So maybe you have a locally cached dependencies and for that you may need to do `mvn -U install` first. 

Let me know if still you are having issues with the current develop branch version of SANSA-RDF.

Best regards,

**Comment by GezimSejdiu** [comment] 2018-05-05 21:29
Hi @antonkulaga ,
it could be because you are using `import $ivy.`net.sansa-stack::sansa-rdf-spark-core:0.3.1-SNAPSHOT` instead of `import $ivy.`net.sansa-stack::sansa-rdf-spark:0.3.1-SNAPSHOT` .
Check it out, on the new version we did a bit of refactoring by simplifying/unifying all SANSA layers to (common, spark, and flink), so you have to remove -core from the dependency and include scala_prefix. See [this](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/pom.xml#L169) as an example how to use it.

**Comment by antonkulaga** [comment] 2018-05-08 11:05
@GezimSejdiu we use the same dataset. I just use:
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.kryo.registrator": "org.bdgenomics.adam.serialization.ADAMKryoRegistrator",
    "spark.kryo.referenceTracking": "true"
in my SparkNotebook because I do bioinformatics and need faster serialization. By now I had not problems with serializations of other libs with such settings

**Comment by GezimSejdiu** [comment] 2018-06-22 09:59
Hi @antonkulaga ,
apologize for the late reply, we were busy with the release process and couldn't continue the discussion here. 
Just by the experience, maybe the issue is coming because of your kryoregistrator is not included on the Spark configuration on the Notebook.
See this as an example of how we did it for the [SANSA-OWL registrator](https://github.com/SANSA-Stack/SANSA-Notebooks/blob/develop/docker-compose.yml#L93).

In case you did it, please could you let me know that still, this persists that we have to investigate more.

Best regards,

**Closed** 2018-07-18 11:04 UTC
Labels: bug
